PASSPHRASE_WORDS = list(dict.fromkeys([
    'amber', 'anchor', 'apple', 'april', 'arch', 'arrow', 'ash', 'atlas', 'atom', 'aurora', 'autumn', 'badge',
    'bamboo', 'barn', 'barrel', 'basin', 'beacon', 'beach', 'bear', 'berry', 'birch', 'bird', 'blaze', 'bloom',
    'blue', 'board', 'boat', 'bolt', 'bonfire', 'book', 'boulder', 'branch', 'breeze', 'brick', 'bridge', 'brook',
    'brush', 'bubble', 'bucket', 'cabin', 'cactus', 'candle', 'cannon', 'canvas', 'canyon', 'captain', 'carpet', 'castle',
    'cedar', 'cellar', 'center', 'chalk', 'charm', 'cheese', 'cherry', 'chest', 'circle', 'clay', 'cloud', 'clover',
    'coast', 'cobalt', 'comet', 'copper', 'coral', 'corner', 'cotton', 'cove', 'crater', 'creek', 'crimson', 'crow',
    'crown', 'crystal', 'current', 'daisy', 'dawn', 'delta', 'desert', 'diner', 'dove', 'draft', 'dragon', 'drift',
    'dune', 'eagle', 'earth', 'echo', 'ember', 'engine', 'evening', 'falcon', 'fawn', 'feather', 'fern', 'field',
    'finch', 'fire', 'fjord', 'flame', 'flare', 'fleet', 'flint', 'flock', 'flower', 'foam', 'forest', 'forge',
    'fox', 'frost', 'galaxy', 'garden', 'gate', 'ghost', 'glade', 'glass', 'glow', 'grain', 'granite', 'grape',
    'grass', 'grove', 'harbor', 'harvest', 'hawk', 'hazel', 'hearth', 'hedge', 'heron', 'hill', 'hollow', 'honey',
    'horizon', 'iceberg', 'ink', 'island', 'ivy', 'jade', 'jasmine', 'jet', 'jewel', 'juniper', 'keeper', 'kettle',
    'key', 'king', 'kite', 'kiwi', 'knight', 'lagoon', 'lake', 'lantern', 'laurel', 'lava', 'leaf', 'legend',
    'lemon', 'library', 'lilac', 'linen', 'lion', 'lizard', 'lodge', 'lotus', 'lunar', 'magic', 'maple', 'market',
    'marble', 'meadow', 'melon', 'mercury', 'mesa', 'meteor', 'midnight', 'mint', 'mirror', 'mist', 'monarch', 'moon',
    'mosaic', 'mountain', 'mouse', 'mulberry', 'murmur', 'nebula', 'nectar', 'needle', 'nest', 'night', 'north', 'nova',
    'oak', 'oasis', 'ocean', 'olive', 'onyx', 'opal', 'orbit', 'orchard', 'otter', 'owl', 'paddle', 'palm',
    'paper', 'path', 'pearl', 'pepper', 'petal', 'phoenix', 'pillow', 'pine', 'planet', 'plaza', 'plume', 'pocket',
    'pond', 'prairie', 'prism', 'pumpkin', 'quartz', 'quill', 'rabbit', 'radar', 'rain', 'raven', 'reef', 'relay',
    'river', 'robin', 'rocket', 'rose', 'rowan', 'ruby', 'saddle', 'sage', 'sail', 'salt', 'sand', 'saturn',
    'scale', 'scarlet', 'school', 'scout', 'sea', 'shadow', 'shell', 'shield', 'shore', 'signal', 'silver', 'sky',
    'slate', 'smoke', 'snow', 'solstice', 'song', 'spark', 'sphere', 'spice', 'spider', 'spirit', 'spring', 'spruce',
    'star', 'station', 'steel', 'stone', 'storm', 'stream', 'street', 'summit', 'sun', 'sunset', 'swallow', 'swift',
    'table', 'talon', 'tangent', 'temple', 'thistle', 'throne', 'thunder', 'tide', 'timber', 'trail', 'train', 'treasure',
    'tree', 'triangle', 'trident', 'tulip', 'tunnel', 'turbine', 'turnip', 'twilight', 'valley', 'velvet', 'venture', 'vine',
    'violet', 'vivid', 'voice', 'volcano', 'voyage', 'walnut', 'water', 'wave', 'whisper', 'willow', 'window', 'wing',
    'winter', 'wolf', 'wood', 'wren', 'yard', 'zephyr', 'acorn', 'alley', 'almond', 'anvil', 'arcade', 'armor',
    'aspen', 'aster', 'aviary', 'awning', 'badge', 'bakery', 'ballad', 'banner', 'beetle', 'bell', 'bench', 'blossom',
    'booth', 'bottle', 'braid', 'bronze', 'butter', 'button', 'cable', 'camel', 'camp', 'caramel', 'cargo', 'carrot',
    'cavern', 'chain', 'chisel', 'chorus', 'cider', 'citadel', 'citrus', 'cliff', 'cloak', 'cocoa', 'compass', 'cookie',
    'cottage', 'cricket', 'dandelion', 'deck', 'denim', 'dew', 'diamond', 'dock', 'dolphin', 'door', 'elm', 'estate',
    'fable', 'factory', 'festival', 'filament', 'firefly', 'flag', 'flour', 'fountain', 'frame', 'furnace', 'garnet', 'glacier',
    'glimmer', 'goose', 'groove', 'harvest', 'helmet', 'hickory', 'honeycomb', 'hotel', 'indigo', 'inlet', 'iron', 'jacket',
    'jungle', 'kernel', 'ladder', 'lakehouse', 'lamp', 'ledger', 'lily', 'locket', 'magnet', 'mallow', 'marina', 'marsh',
    'matrix', 'memory', 'merit', 'mimic', 'minnow', 'minted', 'monsoon', 'muffin', 'museum', 'napkin', 'nickel', 'noodle',
    'noon', 'notebook', 'oakwood', 'obsidian', 'orange', 'origin', 'outpost', 'oxygen', 'panda', 'parade', 'parcel', 'parrot',
    'pasture', 'pebble', 'pencil', 'peppermint', 'pickle', 'pilot', 'pioneer', 'planetary', 'plank', 'plaza', 'poppy', 'porch',
    'postcard', 'puddle', 'ranger', 'raspberry', 'riddle', 'ridge', 'rocketry', 'saffron', 'sapphire', 'scooter', 'seaglass', 'season',
    'shadowbox', 'silk', 'sketch', 'sleet', 'slope', 'socket', 'sonar', 'sorrel', 'sparkle', 'sprinter', 'starlight', 'sunflower',
    'tavern', 'teacup', 'temple', 'terrace', 'ticket', 'topaz', 'torch', 'tower', 'transit', 'treaty', 'truffle', 'tundra',
    'turntable', 'umbrella', 'updraft', 'uplift', 'vanilla', 'vapor', 'vertex', 'violet', 'walrus', 'watch', 'waterfall', 'wheat',
    'wildflower', 'windmill', 'windswept', 'woodland', 'workshop', 'yearling', 'yucca', 'zinnia', 'asteroid', 'backbone', 'backdrop', 'barley',
    'bayou', 'beehive', 'blackbird', 'bluebird', 'bookend', 'bullseye', 'campfire', 'cardinal', 'cashmere', 'catapult', 'causeway', 'chestnut',
    'cloverleaf', 'crosswind', 'daybreak', 'drumbeat', 'earthlight', 'evergreen', 'firebrand', 'firestone', 'flashlight', 'footpath', 'goldenrod', 'grandstand',
    'grapefruit', 'greenhouse', 'groundwork', 'hairpin', 'handshake', 'headland', 'highland', 'honeysuckle', 'jellyfish', 'keyboard', 'landmark', 'lakeside',
    'longbow', 'mainframe', 'moonbeam', 'moonlight', 'nightfall', 'northwind', 'overlook', 'paperback', 'pinecone', 'playbook', 'raindrop', 'rainfall',
    'redwood', 'riverbank', 'sandstone', 'seashore', 'shipyard', 'snowfall', 'songbird', 'starfield', 'starfish', 'starship', 'sunbeam', 'sunrise',
    'tailwind', 'teakettle', 'teardrop', 'thundercloud', 'trailhead', 'undertone', 'watchtower', 'wildfire', 'windstorm', 'wintergreen', 'wonderland', 'woodsmoke'
]))

SEPARATORS = ['-', '.', '_']
SYMBOLS = list('!@#$%^&*+=?')
